name: Whylabs Package Workflow

on:
  push:
    branches: ["mainline"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Run lints and tests on PRs and merges
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: whylabs-toolkit-ci
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.8.15"

      - uses: Gr1N/setup-poetry@v7
        name: Install poetry
        with:
          poetry-version: 1.2.2

      - name: Install python dependencies
        run: make setup

      - name: Check types
        run: make lint

      - name: Check formatting
        run: make format

      - name: Run test
        run: make test
        env:
          ORG_ID : ${{ secrets.ORG_ID }}
          DATASET_ID : ${{ secrets.DATASET_ID }}
          WHYLABS_API_KEY : ${{ secrets.WHYLABS_API_KEY }}
          MONITOR_ID : ${{ secrets.MONITOR_ID }}
          ANALYZER_ID : ${{ secrets.ANALYZER_ID }}
          DEV_WHYLABS_API_KEY: ${{secrets.DEV_WHYLABS_API_KEY}}
          DEV_ORG_ID: ${{secrets.DEV_ORG_ID}}
          DEV_DATASET_ID: ${{secrets.DEV_DATASET_ID}}
