name: Upload Package to PyPi

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install poetry
      uses: Gr1N/setup-poetry@v7
      with:
        poetry-version: 1.2.2

    - name: Install dependencies
      run: |
        make setup
    - name: Build package
      run: | 
        poetry build
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
